version: "3"
services:
  web:
    image: kmenghini/inventory:node
    build: .
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      # restart_policy:
      #   condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet: